
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
# App dependencies
dependencies:
  csv: ^5.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  http: ^1.1.0
  lottie: ^2.5.0
  upi_india: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.15.1
  firebase_remote_config: ^4.2.5
  shared_preferences: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.1.0

flutter:
  uses-material-design : true
  assets:
     - assets/images/flags/
     - assets/lottie/loading.json
     - assets/logo.png
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin-Medium.ttf
          weight: 600
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700
